add weekly changelog 2.253~2.255
jenkins-infra/cn.jenkins.io pull request #310
Opened 2020-09-07 16:57 UTC by zhaoying818

### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [x] [原文地址](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

2020-09-07 16:59 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      全局/系统读取 权限正式变为整体可用 (GA) 状态。
```suggestion
      “全局/系统读取”权限正式变为“整体可用 (GA) ” 状态。
```

2020-09-10 11:50 UTC, yJunS submitted a review, later dismissed

2020-09-12 15:03 UTC, yJunS commented on content/_data/changelogs/lts.yml
> +      This switches agent.jar and remoting.jar to a code-signing certificate owned by the CDF.
这部分都没有翻译呢吧？

2020-09-12 15:17 UTC, zhaoying818 commented on content/_data/changelogs/lts.yml
> +      This switches agent.jar and remoting.jar to a code-signing certificate owned by the CDF.
正在翻译，现在已经翻译完了

2020-09-12 15:24 UTC, yJunS requested changes

2020-09-12 15:24 UTC, yJunS commented on content/_data/changelogs/lts.yml
> +      将 Windows Service Wrapper（WinSW） 从 基于.NET Framework 2.0 的 2.3.0 可执行文件更新为 基于 .NET Framework 4.0 的 2.9.0 版本。
- `从 基于.Net` 从后面应该可以不要空格吧，基于后面加空格可能好一些。
- `更新为 基于` 更新为后面同上

2020-09-13 05:47 UTC, zhaoying818 commented on content/_data/changelogs/lts.yml
> +      将 Windows Service Wrapper（WinSW） 从 基于.NET Framework 2.0 的 2.3.0 可执行文件更新为 基于 .NET Framework 4.0 的 2.9.0 版本。
> * `从 基于.Net` 从后面应该可以不要空格吧，基于后面加空格可能好一些。
> * `更新为 基于` 更新为后面同上

OK

2020-09-13 05:51 UTC, zhaoying818 commented on content/_data/changelogs/lts.yml
> +      将 Windows Service Wrapper（WinSW） 从 基于.NET Framework 2.0 的 2.3.0 可执行文件更新为 基于 .NET Framework 4.0 的 2.9.0 版本。
```suggestion
      基于 .NET Framework 2.0 的  Windows Service Wrapper（WinSW） 2.3.0 可执行文件更新为 基于 .NET Framework 4.0 的 2.9.0 版本。
```

2020-09-15 07:28 UTC, yJunS approved these changes

2020-09-15 07:28 UTC, merged