add weekly changelog 2.261~2.262
jenkins-infra/cn.jenkins.io pull request #314
Opened 2020-10-20 14:55 UTC by zhaoying818

### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [x] [原文地址](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

2020-10-20 14:58 UTC, LinuxSuRen approved these changes
LGTM

2020-10-22 12:08 UTC, yJunS requested changes

2020-10-22 12:08 UTC, yJunS commented on content/_data/changelogs/weekly.yml
> +      繁体中文翻译中的“从”引用替换为“代理”。
`slave` 和 `agent` 建议不做翻译，原文中也没做这个翻译
![image](https://user-images.githubusercontent.com/20575981/96869099-98c0e280-14a1-11eb-8789-70caa6b2335f.png)

2020-10-22 12:08 UTC, yJunS commented on content/_data/changelogs/weekly.yml
> +      使用“代理到控制器”来描述代理访问控制系统，而不是“代理到主控”。
`Agent to controller` 和 `agent to master`也建议不直接做翻译，前面还稍微好理解些，后面的看内容不太容易理解，感觉直接写出来会略微好理解些

2020-10-22 13:42 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      使用“代理到控制器”来描述代理访问控制系统，而不是“代理到主控”。
```suggestion
      使用 “Agent to controller” 来描述代理访问控制系统，而不是 “Agent to master”。
```

2020-10-22 13:42 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      繁体中文翻译中的“从”引用替换为“代理”。
```suggestion
      繁体中文翻译中的 “slave” 引用替换为 “agent”。
```

2020-10-23 07:29 UTC, yJunS approved these changes
LGTM

2020-10-23 07:31 UTC, merged