add weekly changelog 2.264
jenkins-infra/cn.jenkins.io pull request #316
Opened 2020-10-28 14:06 UTC by zhaoying818

### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [x] [原文地址](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

2020-11-15 15:32 UTC, yJunS requested changes

2020-11-15 15:32 UTC, yJunS commented on content/_data/changelogs/weekly.yml
> +      内部: 更正对 <code>TokenUuidAndPlainValue</code>.的限制范围。
`.的`多了个.吧？

2020-11-15 15:32 UTC, yJunS commented on content/_data/changelogs/weekly.yml
> +      对资源根 URL 设置进行少量英语清除。
感觉这句话不是很好理解的样子

2020-11-17 14:46 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      内部: 更正对 <code>TokenUuidAndPlainValue</code>.的限制范围。
```suggestion
      内部: 更正对 <code>TokenUuidAndPlainValue</code> 的限制范围。
```

2020-11-17 15:08 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      对资源根 URL 设置进行少量英语清除。
```suggestion
      对英文资源根 URL 设置进行少量清理。
```

2020-11-17 15:39 UTC, yJunS approved these changes
LGTM

2020-11-17 15:39 UTC, merged