add weekly changelog 2.272~2.273
jenkins-infra/cn.jenkins.io pull request #321
Opened 2021-01-05 02:58 UTC by zhaoying818

### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [x] [原文地址](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

2021-01-14 14:56 UTC, yJunS requested changes

2021-01-14 14:56 UTC, yJunS commented on content/_data/changelogs/lts.yml
> +      帮助文本现在扩展了GitHub组织文件夹的行为(由 2.244 引入的缺陷回归)。
`GitHub` 两边没有加空格

2021-01-14 14:56 UTC, yJunS commented on content/doc/upgrade-guide/2.263.adoc
> +NOTE: 者并_不_意味着这些漏洞不再是问题，利用将变得更加困难，例如，它们可能需要额外的权限才能设置。
`者` -> `这`

2021-01-16 02:31 UTC, zhaoying818 commented on content/doc/upgrade-guide/2.263.adoc
> +NOTE: 者并_不_意味着这些漏洞不再是问题，利用将变得更加困难，例如，它们可能需要额外的权限才能设置。
```suggestion
NOTE: 这并_不_意味着这些漏洞不再是问题，利用将变得更加困难，例如，它们可能需要额外的权限才能设置。
```

2021-01-16 02:31 UTC, zhaoying818 commented on content/_data/changelogs/lts.yml
> +      帮助文本现在扩展了GitHub组织文件夹的行为(由 2.244 引入的缺陷回归)。
```suggestion
      帮助文本现在扩展了 GitHub 组织文件夹的行为(由 2.244 引入的缺陷回归)。
```

2021-01-16 15:58 UTC, yJunS approved these changes

2021-01-16 15:58 UTC, merged