add weekly changelog 2.276
jenkins-infra/cn.jenkins.io pull request #322
Opened 2021-01-24 14:10 UTC by zhaoying818

### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [x] [原文地址](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

2021-02-01 01:59 UTC, LinuxSuRen requested changes

2021-02-01 01:59 UTC, LinuxSuRen commented on content/_data/changelogs/weekly.yml
> +      Provide a default implementation of the "all files in zip" download link.
看起来部分内容还没有翻译，再帮忙完善下吧。辛苦了

2021-02-01 02:00 UTC, LinuxSuRen commented
/on-hold

2021-02-01 02:03 UTC, LinuxSuRen commented
/hold

2021-02-01 14:50 UTC, zhaoying818 commented on content/_data/changelogs/weekly.yml
> +      Provide a default implementation of the "all files in zip" download link.
> 
> 
> 看起来部分内容还没有翻译，再帮忙完善下吧。辛苦了

粗心大意。没有翻译的那不是是2.276，忘了删除原文了，已经修复！

2021-02-02 00:51 UTC, LinuxSuRen commented
/lgtm

2021-02-02 00:55 UTC, LinuxSuRen commented
/approve

2021-02-02 01:23 UTC, LinuxSuRen commented
/approve

2021-02-02 01:27 UTC, merged